projectType: extension
additionalTestConfigs:
  jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DminVersion=4.3.0
  jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DminVersion=4.6.0