projectType: extension
mavenAdditionalArgs: -DincludeSnapshots=false -DminVersion=4.3.0
buildTimeoutTime: 8
buildTimeoutUnit: HOURS
additionalTestConfigs:
  jdk11:
    testJdkTool: OPEN-JDK11 # TODO: Remove -DruntimeVersion=4.8.5 once Mule Runtime 4.9.3 is working with JDK 11
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DruntimeVersion=4.8.5
  jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DminVersion=4.6.0